### ISSUE TITLE
调度器安排优化2024.6.22

### ISSUE THREAD

**Issue by heidon-sensei** [pur1fying/blue_archive_auto_script#101]
1. “收集每日体力”并入“收集奖励”并保持优先级为4
2. “收集每日体力”重置时间增加9.3.1（100%解决17点登陆问题）
### **3. 调度器配置不知为何每次更新后都会重置（调度器填写的配置是有效的）** 
4. 调度器“详细配置”又出现填写完后没有实时更新的现象（可能是更新的问题，更新完后正常，附更新图）
![IMG_20240622_111916](https://github.com/pur1fying/blue_archive_auto_script/assets/162718826/8b255d40-90c8-4ed3-b256-5f8a5eb4f5d0)

**Comment by KarylDAZE** [comment]
关于3：
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/50506792/92dcc775-52cd-41ff-ba8d-c7a7480ed981)

**Comment by heidon-sensei** [comment]
关于3：
也许可以尝试将数据在baas内自动修正后全部复制到txt文件中，例：
刷新时间2024-1-1 1:00:00
自动改正为2024-01-01 01:00:00（防呆）
数据可以按照“事件”分成多个文件，也可以合并
关于加载数据的话，我记得python是可以修改程序内容的，但是如果baas只有少量py文件而不细分模块，
###  **当我没说**

**Comment by KarylDAZE** [comment]
实际上config\1708148000\event.json存储了调度时间，而这个文件每次启动baas时被重置导致调度器重置。手动恢复的话只需要在启动baas前把event.json备份一遍，启动后用备份文件覆盖重置后的文件即可
