### ISSUE TITLE
baas启动时，加入对模拟器是否已经在运行中的检测

### ISSUE THREAD

**Issue by KarylDAZE** [pur1fying/blue_archive_auto_script#102]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/50506792/a73feedd-102b-4d88-8496-00b35b0009f4)

![image](https://github.com/pur1fying/blue_archive_auto_script/assets/50506792/26b15961-b6f4-4f3c-9660-eae4e880b651)
启动baas时，即使模拟器已经正在运行，仍会等待“等待模拟器启动时间”后才运行调度任务。希望可以首先检测模拟器是否正在运行，如果是则直接执行调度任务

**Comment by Daodanfd5** [comment]
这个模块是我做的 应该后续我会先把检测是否已添加扔进来 等后续开发吧

**Comment by Daodanfd5** [comment]
> ![image](https://private-user-images.githubusercontent.com/50506792/343711709-a73feedd-102b-4d88-8496-00b35b0009f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDkxNzksIm5iZiI6MTcyNjU0ODg3OSwicGF0aCI6Ii81MDUwNjc5Mi8zNDM3MTE3MDktYTczZmVlZGQtMTAyYi00ZDg4LTg0OTYtMDBiMzViMDAwOWY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA0NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiYjQzOWFlOTA3ZGZkOWZhYTI2OTUzMmI3Y2UyNmY4Mzg5NDU3Mjg2N2Q4OGJlZjJiNGNjMjZmZjQ2MTljYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wjptRfk2ld2vmLIrhyfSXiKlfXhZSHOr2lFfXNq4nHQ)
> 
> ![image](https://private-user-images.githubusercontent.com/50506792/343709821-26b15961-b6f4-4f3c-9660-eae4e880b651.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NDkxNzksIm5iZiI6MTcyNjU0ODg3OSwicGF0aCI6Ii81MDUwNjc5Mi8zNDM3MDk4MjEtMjZiMTU5NjEtYjZmNC00ZjNjLTk2NjAtZWFlNGU4ODBiNjUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA0NTQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYjhhZGQ4MmFjMzVlNjY3OTkyMDNhOGM2MTE0OGFjZThhMzc3M2FlMTU0ZjYyMjc4YjY2MDEyZjFlNjkwODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_RKnAl2gQqK_lKt2PaPTnuxGHL3v2PmkaXIP8sAT6E) 启动baas时，即使模拟器已经正在运行，仍会等待“等待模拟器启动时间”后才运行调度任务。希望可以首先检测模拟器是否正在运行，如果是则直接执行调度任务

模块已更新，等待启动部分的相关逻辑

**Comment by Daodanfd5** [comment]
device_operation包已更新，现在在启动模拟器时可以返回对应模拟器的启动状态了
@pur1fying 有空的话记得改一下启动，调用方式：
device_operation.start_simulator_classic(simulator_type, multi_instance , return_status=True)
然后返回的值是一个列表，第一个是启动状态，第二个是adb连接地址
