### ISSUE TITLE
咖啡厅摸头问题

### ISSUE THREAD

**Issue by PeiyeYang** [pur1fying/blue_archive_auto_script#103]
我的截图间隔设置为0.3s，摸头操作的match方法返回结果为空。经过测试
cafe_reward.py line 101 "self.swipe(131, 660, 1280, 660, duration=0.5)" 时，match方法的输入截图为
![屏幕截图 2024-07-02 134847](https://github.com/pur1fying/blue_archive_auto_script/assets/96364128/c27a6aa1-16f3-4c73-8958-1e88aeaa17f2)
可以看出截图时刻为拖动完礼物后，改为"duration=1"后，match方法的输入截图为
![屏幕截图 2024-07-02 135043](https://github.com/pur1fying/blue_archive_auto_script/assets/96364128/5e43f63c-b1f0-4062-8971-4e95bea6435c)
此时可以正常摸头。

**Comment by pur1fying** [comment]
最近是有很多人反馈这个问题。

原因是u2在一些模拟器上执行cafe_reward.py line 101这一步滑动过快(少于一秒截图延迟) 
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/6360b619-bc22-4e1d-a029-44c0b9786ddf)
导致line 81截图没有截到笑脸露出的画面
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/e9cdef4c-9860-4022-a4d0-597828e88e04)

目前想到的可能解决方案是：
1.记录一次swipe的时间，如果当次没有match到就根据swipe时间调整截图延迟，并再次滑动match
2.拉高swipe时间

不过我目前暂时没有遇到这个问题，可以的话可以给出稳定复现的配置以便调试，能提pr当然更好 ovo

btw:7月8日期末考完再考虑修复

**Comment by PeiyeYang** [comment]
模拟器：MuMu模拟器12 v3.9.2 (3069)
分辨率设置：1920*1080
帧率设置：60（成功摸头）120（失败）240（失败）

同时，商店购买设置为所有强化珠和欧帕兹时，60帧率下成功，120帧率下失败

猜测相同duration，不同帧率下，滑动操作是不一样的

**Comment by pur1fying** [comment]
通过动态调整截图延迟已经成功在高帧率下咖啡厅摸头，商店购买我试了全选好像没有问题？
![image](https://github.com/user-attachments/assets/917bad4d-ed22-44a9-ad26-9b02a81b12f2)

**Comment by PeiyeYang** [comment]
120帧率下，使用以下商店购买设置
![屏幕截图 2024-07-17 133635](https://github.com/user-attachments/assets/64087dc3-7326-4743-b1d7-5ec40ebfdbb4)
结果录屏如下
https://github.com/user-attachments/assets/af61ed08-5ce5-4c9c-9d66-0b1eec0b516c

第一次滑动后，点击商品都点击在了购买选项上，会弹出购买通知窗口导致导致后续商品多选点击失效。
第二次滑动后到最底部后，可以正常点击并多选商品购买。
