### ISSUE TITLE
自定义adb ip地址

### ISSUE THREAD

**Issue by xingxing-tang** [pur1fying/blue_archive_auto_script#106]
在部分模拟器启用“网络桥接”功能后，由于BAAS只能连本地回环地址的设备，所以BAAS无法使用。请求允许自定义adb连接的ip地址。
![Clip_2024-07-07_10-21-54](https://github.com/pur1fying/blue_archive_auto_script/assets/122072018/c6a446fb-fe8f-40a2-82b4-b7088dd9d460)

**Comment by Daodanfd5** [comment]
这个问题我很早之前就在开发群提过一嘴 不过并没有回应（x
之前针对wsa设备的设定的时候就有使用tcp socket是否超时进行探测的设计了
然后那个时候我就说了加个usb设备和非本机无线调试设备的支持
现在看来应该只能曲线救国使用本地代理（frpc +frps）把本地设定为目标ip+目标端口远程设定为本机127.0.0.1然后随机设定一个端口

很麻烦倒是
等后面实现吧

**Comment by Kiramei** [comment]
看到问题了，目前准备添加一项“ADB 自定义IP”配置项解决该问题

**Comment by Kiramei** [comment]
已经添加
