### ISSUE TITLE
提示购买月卡界面卡住

### ISSUE THREAD

**Issue by KarylDAZE** [pur1fying/blue_archive_auto_script#109]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/50506792/24feb9dc-b1c7-4f05-b3c4-ca3b3c702097)
执行凌晨四点重启后，如果弹出提示续费月卡界面会无法识别

**Comment by KarylDAZE** [comment]
1280*720截图：
![月卡续费](https://github.com/user-attachments/assets/619b72c1-ed3e-4dd4-8533-ced7f973f7cf)

**Comment by pur1fying** [comment]
已添加
