### ISSUE TITLE
Web控制台支持/CLI运行指南

### ISSUE THREAD

**Issue by CNflysky** [pur1fying/blue_archive_auto_script#114]
首先对各位开发者表示感谢，没有你们就没有这样优秀的项目。
我的使用场景是将游戏和脚本都挂在服务器（Linux ARM64）上运行，请问本项目是否提供了像是alas（碧蓝航线自动脚本）的web控制台或者是命令行运行文档？

**Comment by pur1fying** [comment]
你好，暂时没有在 Linux 环境或云端尝试过部署，在这方面还不是特别了解，想问下问题是否在于Linux无法运行 .exe后缀文件而无法启动gui，所以必须要用命令行启动？

**Comment by CNflysky** [comment]
> 你好，暂时没有在 Linux 环境或云端尝试过部署，在这方面还不是特别了解，想问下问题是否在于Linux无法运行 .exe后缀文件而无法启动gui，所以必须要用命令行启动？

是的，我看项目的GUI是用qt写成，Linux运行qt程序需要桌面环境（x11）之类，而无头服务器安装gui不是很方便。因此想请教一下是否有手动编辑配置文件然后使用cli命令手动配置运行本项目的方法。

**Comment by pur1fying** [comment]
手动配置可能无法保证配置合法（许多配置是ui层接收到用户输入后修改并保证合法的），建议在可以运行ui的地方生成并修改配置，然后复制config文件夹到服务器上baas对应路径，然后运行main.py（需要安装好python和对应库）
![image](https://github.com/user-attachments/assets/bddefec4-fd97-4138-8779-b669fbe1b496)

**Comment by CNflysky** [comment]
> 手动配置可能无法保证配置合法（许多配置是ui层接收到用户输入后修改并保证合法的），建议在可以运行ui的地方生成并修改配置，然后复制config文件夹到服务器上baas对应路径，然后运行main.py（需要安装好python和对应库）
> ![image](https://github.com/user-attachments/assets/bddefec4-fd97-4138-8779-b669fbe1b496)
> 

非常感谢，稍后我会进行尝试。
