### ISSUE TITLE
自动运行

### ISSUE THREAD

**Issue by xzy577** [pur1fying/blue_archive_auto_script#116]
希望能有开机自启功能和自动运行的功能

**Comment by Daodanfd5** [comment]
在做了
开机自启baas只需要把baas快捷方式扔进C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp即可
自动启动的话需要加个配置应该

**Comment by VoltIcaRus** [comment]
@Daodanfd5 Is there any option to shut down BA after all the task is done?

**Comment by RedDeadDepresso** [comment]
@VoltIcaRus I'm already working on it. You can [try](https://github.com/RedDeadDepresso/blue_archive_auto_script) it if you want. I'll make a pull request in a few days.

**Comment by Daodanfd5** [comment]
> @Daodanfd5 Is there any option to shut down BA after all the task is done? My mini pc really needs this option because the cooler noise is loud

The scheduler is running 24 hours a day. There is no function to shut down ba for the time being. A better scheduler may be designed for this request.

**Comment by Daodanfd5** [comment]
> @VoltIcaRus I'm already working on it. You can [try](https://github.com/RedDeadDepresso/blue_archive_auto_script) it if you want. I'll make a pull request in a few days.

I saw your fork, and there is a problem in stopping simulator. If there are multiple instances running, this will close all the instance with same process name, and it seems to require a privilege to terminate other process(at least on my machine)

There is a module in .device_operation that can distinguish between multiple instances and shut down the emulator individually (MuMu12 and BlueStacks supported,and more in the future)
