### ISSUE TITLE
国际服咖啡厅无法检测interaction

### ISSUE THREAD

**Issue by weibaozi** [pur1fying/blue_archive_auto_script#124]
![image](https://github.com/user-attachments/assets/e8b28b80-ecf8-4234-8aea-3675487f0e5a)
如图所示,拖礼物是可以看见笑脸,但是检测不到,之前还能用,前几天更新后就不行了

**Comment by weibaozi** [comment]
发现问题了,配置文件里cafe delay变成-0.3了,看了下代码估计之前不知道怎么回事overwrite了,改回来就好了
![image](https://github.com/user-attachments/assets/dc684a95-6183-473d-ae61-6c6718b166ae)

**Comment by weibaozi** [comment]
应该是这里,cafe_reward.py 115行
![image](https://github.com/user-attachments/assets/98b95ba1-2c89-41cf-a7ab-21ed07d1ac4f)

**Comment by pur1fying** [comment]
想了一下应该是某次你在运行咖啡厅时点击了停止，导致该次swipeT为0，然后对应配置被改为-0.3，是否有这样的情况？

**Comment by weibaozi** [comment]
> 想了一下应该是某次你在运行咖啡厅时点击了停止，导致该次swipeT为0，然后对应配置被改为-0.3，是否有这样的情况?

有可能,但是swipe没执行后面应该也不会执行吧
