### ISSUE TITLE
是否应该将“调度配置填写”帮助文档在GUI中展示

### ISSUE THREAD

**Issue by KarylDAZE** [pur1fying/blue_archive_auto_script#125]
src\descriptions\调度配置填写帮助.html应该放入src\descriptions\zh_CN，否则用户无法从GUI的帮助界面中获取该文档
![image](https://github.com/user-attachments/assets/7e3afd8a-a1c0-49cb-85ba-1a835977e091)

**Comment by pur1fying** [comment]
已修正
