### ISSUE TITLE
调度器UI时间输入框优化

### ISSUE THREAD

**Issue by KarylDAZE** [pur1fying/blue_archive_auto_script#126]
![image](https://github.com/user-attachments/assets/24e376e4-9c07-48a7-9eee-f94a7200f50c)
目前调度器是随光标移动而改变聚焦输入框，容易导致在手动填入时间时移动鼠标而输入到了非目标输入框。
期望结果是改为鼠标点击才会改变聚焦输入框。

**Comment by Kiramei** [comment]
已解决
