### ISSUE TITLE
功能请求 添加活动推图所需属性

### ISSUE THREAD

**Issue by yukiryo** [pur1fying/blue_archive_auto_script#127]
![image](https://github.com/user-attachments/assets/e43798e0-6adc-454e-a772-8e64c6dbbddc)

**Comment by Kiramei** [comment]
请详细且具体描述你的问题，我们无法定位你的诉求。

**Comment by Kiramei** [comment]
功能目前已推至Temp分支。

**Comment by Kiramei** [comment]
@pur1fying 请审查该Commit：f60c394626798bb206d6b9e74b2b0946f148eb10，我在运行中会产生卡顿。

**Comment by Kiramei** [comment]
已完成。
