### ISSUE TITLE
競技場挖石頭卡住

### ISSUE THREAD

**Issue by Michael-Kao** [pur1fying/blue_archive_auto_script#129]
競技場排名前進時會卡在領取石頭畫面
![PVPBug](https://github.com/user-attachments/assets/ed69623f-0ce0-46bc-9404-7b175fc9e722)
![MuMu12-20240731-232704](https://github.com/user-attachments/assets/2264ef3b-736d-4e31-96aa-7194d3dbc3f4)

**Comment by pur1fying** [comment]
应该在这个 commit dc84c40fb392dcbeb1eb8292781ac3204988a975 之后就好了
