### ISSUE TITLE
抓不到mumu模擬器

### ISSUE THREAD

**Issue by Michael-Kao** [pur1fying/blue_archive_auto_script#140]
腳本可以偵測到目前開啟的adb地址,但是會判定模擬器未啟動
如果把模擬器關閉後再啟動腳本, 腳本不會自己啟動模擬器

沒記錯的話最後使用時間是8/18號, 有嘗試將腳本回退版本到8/18, 但不清楚如何打開腳本且不自動更新

![image](https://github.com/user-attachments/assets/242254fa-203b-4119-b345-8a6fda5748c7)
![image](https://github.com/user-attachments/assets/71fdc4af-d9f4-465a-894c-729fda3599f2)
![image](https://github.com/user-attachments/assets/c4cb601a-88a3-462d-b9dd-a0dbd14b4e24)

**Comment by pur1fying** [comment]
1.adb ip 填写127.0.0.1
2.选择是否多开 开
模拟器类型 mumu模拟器 多开号 1 试试

**Comment by Michael-Kao** [comment]
正常了
謝謝
