### ISSUE TITLE
Emulator Initialization Failed - Global Server

### ISSUE THREAD

**Issue by vRinzler** [pur1fying/blue_archive_auto_script#145]
Hello!
I've been using your script for a long time, and today, after your update to support the New Year's Apperitif event, BAAS refused to connect to my emulator, despite it doing fine before the update. Below is my emulator configuration with MuMu Player 12 CN, and BAAS failed to recognize my Global package.
I hope you can take a look at this issue.
Thank you very much!

![Screenshot 2024-09-06 202451](https://github.com/user-attachments/assets/a0148750-f384-4cea-adc9-754f6baf8c76)
![Screenshot 2024-09-06 202503](https://github.com/user-attachments/assets/c487177d-1876-4e5a-9af9-fcbb74fe42e5)

**Comment by vRinzler** [comment]
Additionally, after the update, I did see these 2 new Chinese settings called Screenshot Mode and Control Mode with options of ADB, nemu and UIAutomator2. What should I use and how are these different from each other?
![image](https://github.com/user-attachments/assets/df29dc9e-4b40-43d0-80f0-c5819f013591)

**Comment by pur1fying** [comment]
> Hello! I've been using your script for a long time, and today, after your update to support the New Year's Apperitif event, BAAS refused to connect to my emulator, despite it doing fine before the update. Below is my emulator configuration with MuMu Player 12 CN, and BAAS failed to recognize my Global package. I hope you can take a look at this issue. Thank you very much!
> 
> ![Screenshot 2024-09-06 202451](https://private-user-images.githubusercontent.com/180668197/365185258-a0148750-f384-4cea-adc9-754f6baf8c76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg4MzIsIm5iZiI6MTcyNTYzODUzMiwicGF0aCI6Ii8xODA2NjgxOTcvMzY1MTg1MjU4LWEwMTQ4NzUwLWYzODQtNGNlYS1hZGM5LTc1NGY2YmFmOGM3Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjljYWNhNmRmZmIxZTJkNDY0MGI5MjhlNWQ0N2Y4ZjFkNWRjMDYwNTE5MGE0YjQ0MTI1NjFiNmY0NjAxNjAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.V78ZEYqkU3MIV9vCwM37HX96dpohcYkbIvayzdEEhss) ![Screenshot 2024-09-06 202503](https://private-user-images.githubusercontent.com/180668197/365185275-c487177d-1876-4e5a-9af9-fcbb74fe42e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzg4MzIsIm5iZiI6MTcyNTYzODUzMiwicGF0aCI6Ii8xODA2NjgxOTcvMzY1MTg1Mjc1LWM0ODcxNzdkLTE4NzYtNGU1YS05YWY5LWZjYmI3NGZlNDJlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNjAyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kN2VjNjg1ZTljOGNkMGY2Y2ViNmI4OGExYjkwZTFjNTM1MmVlMDI2OWQ0ZjkxZjhmYWViYzU5ZDA5NmI4NWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2aiHzfPc2TquMvpM7oytsToRJpW8riTsvdEwLt-5Zrg)

Please try again and it shall be fixed.



> Additionally, after the update, I did see these 2 new Chinese settings called Screenshot Mode and Control Mode with options of ADB, nemu and UIAutomator2. What should I use and how are these different from each other? ![image](https://private-user-images.githubusercontent.com/180668197/365213618-df29dc9e-4b40-43d0-80f0-c5819f013591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2Mzc5NjEsIm5iZiI6MTcyNTYzNzY2MSwicGF0aCI6Ii8xODA2NjgxOTcvMzY1MjEzNjE4LWRmMjlkYzllLTRiNDAtNDNkMC04MGYwLWM1ODE5ZjAxMzU5MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNlQxNTQ3NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzkxMjBiZTg1NDQzY2I2OTkyMTU2NGM5ZDRkZmMwZmVjYTEyNTk1NWFmNDYxZTljMWQ3YzFiN2E5OGU4NTUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._qlyvISgn171FPgjNEOB-a1fStkJ__YNV42hH1RKv7I)

I will give more descriptions to help choose different screenshot and  control method, since there will be some bug with other method, please just choose uiautomator2 and script will work as it used to do,

**Comment by vRinzler** [comment]
This is after the update, I had checked the update log to make sure I had the patch, but it still fails to recognize my package.
What are your testing conditions? I tried a full reinstall of BAAS but it still has this issue.
Before this update, I had the ATX app installed to my emulator. I did find it in the tmp folder, located in BAAS folder, install it manually and tried starting both ATXAgent and UIAutomator but both didn't work.
![image](https://github.com/user-attachments/assets/8663c8d4-da38-4215-a3f3-0dc6fd8bb93e)

**Comment by pur1fying** [comment]
Please reopen the exe and try again

**Comment by vRinzler** [comment]
After testing this morning I can confirm that the script is working as intended again, with one minor issue:
When bond tapping in Cafe, the tapping position for dragging gifts is out of position if the scrren is set to anyting bigger than 1280x720, which was not the case when I used the script before at 1920x1080. Can you take a look into it?

**Comment by pur1fying** [comment]
It should be ok now

**Comment by vRinzler** [comment]
Everything is back to normal, thank you very much!
