### ISSUE TITLE
咖啡厅邀请学生时无法识别到圣园未花

### ISSUE THREAD

**Issue by Neutralization** [pur1fying/blue_archive_auto_script#148]
INFO | 2024-09-17 11:38:47 | Invite ticket available for use 
    INFO | 2024-09-17 11:38:47 | Inviting : ['ミカ'] 
    INFO | 2024-09-17 11:38:47 | find cafe_menu 
    INFO | 2024-09-17 11:38:47 | click (838  ,  647) 
    INFO | 2024-09-17 11:38:48 | end : cafe_invitation-ticket 
    INFO | 2024-09-17 11:38:48 | Begin Find Student ミカ 
    INFO | 2024-09-17 11:38:50 | Detected name : [ シロコ,アカリ,イオリ,ノノミ ] 
    INFO | 2024-09-17 11:38:50 | Didn't Find Target Student Swipe to Next Page 
    INFO | 2024-09-17 11:38:50 | swipe from ( 412 , 580 ) --> ( 412 , 150 ) 
    INFO | 2024-09-17 11:38:51 | click (412  ,  500) 
    INFO | 2024-09-17 11:38:53 | Detected name : [ ウタハ,コタマ,ツバキ,ハナコ水着,モモイ ] 
    INFO | 2024-09-17 11:38:53 | Didn't Find Target Student Swipe to Next Page 
    INFO | 2024-09-17 11:38:53 | swipe from ( 412 , 580 ) --> ( 412 , 150 ) 
    INFO | 2024-09-17 11:38:54 | click (412  ,  500) 
    ..................
    INFO | 2024-09-17 11:40:02 | Detected name : [ サキ水着,ツルギ水着,ノドカ,ヒビキ応援団 ] 
    INFO | 2024-09-17 11:40:02 | Didn't Find Target Student Swipe to Next Page 
    INFO | 2024-09-17 11:40:02 | swipe from ( 412 , 580 ) --> ( 412 , 150 ) 
    INFO | 2024-09-17 11:40:03 | click (412  ,  500) 
    INFO | 2024-09-17 11:40:04 | Detected name : [ ノドカ,ヒビキ応援団,フブキ ] 
    INFO | 2024-09-17 11:40:04 | Didn't Find Target Student Swipe to Next Page 
    INFO | 2024-09-17 11:40:04 | swipe from ( 412 , 580 ) --> ( 412 , 150 ) 
    INFO | 2024-09-17 11:40:05 | click (412  ,  500) 
    INFO | 2024-09-17 11:40:06 | Detected name : [ フブキ ] 
    WARNING | 2024-09-17 11:40:06 | Already swipe to the end of the list 
    WARNING | 2024-09-17 11:40:06 | Can't Detect Target Student : [ ミカ ].

![Snipaste_2024-09-17_11-40-29](https://github.com/user-attachments/assets/1de12e2e-cfe0-4548-b2c8-d05e59168885)
![Snipaste_2024-09-17_11-40-56](https://github.com/user-attachments/assets/e18eb9ff-1a49-4502-8d16-bcc251ce5d2e)

**Comment by pur1fying** [comment]
后续添加一个邀请第一个收藏的角色吧（，只需要把需要的角色设为收藏就行了

**Comment by pur1fying** [comment]
现在可以设置咖啡厅邀请收藏的角色
