### ISSUE TITLE
程序启动检查更新时 git 版本问题更新失败

### ISSUE THREAD

**Issue by Neutralization** [pur1fying/blue_archive_auto_script#149]
启动时会读取系统的 gitconfig 文件，由于自带 git 版本问题不支持 gpg.format=ssh 配置项

>[gpg]
>	format = ssh

![Snipaste_2024-09-16_01-14-22](https://github.com/user-attachments/assets/e8ebbe83-5d10-4d41-a70d-4926009c612a)

于是拉取更新失败后正常启动。
测试了更新自带 git 版本后能正常拉去更新。

搜索到有忽略系统配置的方法，不确定可行性。
[Run git commands without default gitconfig](https://superuser.com/questions/53030/run-git-commands-without-default-gitconfig)

**Comment by Arcelibs** [comment]
問下如何更新自帶git版本?

**Comment by pur1fying** [comment]
> 問下如何更新自帶git版本?

下载新版本git并替换toolkit目录下的git

**Comment by Kiramei** [comment]
本项目最新Release采用了Dulwich，无需Git本体即可运行。 #158
