### ISSUE TITLE
详细配置修改不成功

### ISSUE THREAD

**Issue by AutoLoop255** [pur1fying/blue_archive_auto_script#152]
在详细配置中调整每日重置时间，弹出修改完成，但是重新点开后又恢复了原样
事实上，整个“详细配置”修改完成后都会恢复原样。
![1](https://github.com/user-attachments/assets/a2481eec-4744-4a3f-8c5d-2b776a0819d7)
![2](https://github.com/user-attachments/assets/661cf345-8073-48ad-982b-63b763f32355)

此外，对于竞技场部分，应该在下午1点（国际服时间）增加每日重置，以便领取奖励，而不是在第二天重置领取

其实在“新的配置”一栏中已经适配了国际服的时间（凌晨3点刷新），我觉得可以把“新的配置”一栏直接重命名成“国际服”，这样其实更加好
![3](https://github.com/user-attachments/assets/43f4d212-193e-4a3d-a5fd-750baabfa9c7)

**Comment by Kiramei** [comment]
对于你说的第二点，“新的配置”这个名字可以在创建该配置的时候命名为“国际服”，目前正在思考配置名更新的问题。
第一个问题已解决。

**Comment by Kiramei** [comment]
#154 目前已在这个PR中增添相应修改方式
