### ISSUE TITLE
新增功能设置为默认关闭

### ISSUE THREAD

**Issue by xzy577** [pur1fying/blue_archive_auto_script#166]
我的基本情况：电脑是每天自动开机，开机后自动打开baas，打开后自动运行脚本。bass只负责最简单机械的事，我手动打总力战、考试、活动推图等。

遇到的问题：今天更新了自动打考试的功能，中午上线准备打考试的时候，就发现bass已经用平时打一档的阵容自动打了个16档的成绩。希望上线新功能能默认关闭。

**Comment by ERROR0cai** [comment]
我也觉得哦~我是电脑一直开机但Baas定时执行，结果半夜起床上厕所的时候（不应该是Baas的执行时间段）发现Baas还在动，一看怎么有个新功能开着（😂）

**Comment by FragileCodes** [comment]
我也遇到了，亏了75币。
希望以后能在更新某个功能的时候，不管原本那个功能的调度是打开还是关闭的，都设置为关闭，因为上次国服日程更新百鬼夜行区域的时候，日程的配置就被静默地改成了全是1了，没有检查结果就每个都做了一次。
或者在更新功能的时候能够弹出更新提示之类的，目前这种静默更新+强制更新的情况下，希望至少能自动把调度给关闭。

**Comment by Kiramei** [comment]
在 867cd50d16338ae64285ef594002239aca3d3609 中，新添了选择功能的UI选项框。

![image](https://github.com/user-attachments/assets/87f49c50-c94b-4003-b2d3-bbacb1f287b6)
