### ISSUE TITLE
无法自动关闭物品过期提示

### ISSUE THREAD

**Issue by XcantloadX** [pur1fying/blue_archive_auto_script#167]
![1730087283909](https://github.com/user-attachments/assets/c64f9408-ce49-4e7b-b215-d0175d7ca400)

**Comment by ERROR0cai** [comment]
确实，我昨天也遇见了，哈哈哈
![image](https://github.com/user-attachments/assets/fe2c056e-108f-4976-945e-af4f751b0809)

**Comment by ERROR0cai** [comment]
我有一个不成熟的想法，就是检测到在某界面停留太久或者等待触发器等待了很久，就直接注入系统返回键，因为ba里面大多数界面都可以用系统返回键返回，这样可以不管点击哪里（当然我只是随便说说）

**Comment by pur1fying** [comment]
请提供1280x720截图

**Comment by XcantloadX** [comment]
物品已经过期了，只能等下次活动结束再截图。

先把已经过期的提示放上来：
![Screenshot_20241029-163249](https://github.com/user-attachments/assets/c2c86790-13bb-422d-8d83-efa347d2bc1c)

**Comment by heidon-sensei** [comment]
这个我其实很久以前反馈过，只不过说物品变化快没必要搞这个

**Comment by XcantloadX** [comment]
![Screenshot_20241104-123936](https://github.com/user-attachments/assets/5d67ea7e-db03-464d-995a-9004aa6cae0f)

**Comment by pur1fying** [comment]
https://github.com/pur1fying/blue_archive_auto_script/issues/176#issuecomment-2495473925
