### ISSUE TITLE
国际服竞技场商店无法刷新

### ISSUE THREAD

**Issue by REAmamiyaFD** [pur1fying/blue_archive_auto_script#170]
mumu模拟器12分辨率设置1920x1080
国际服竞技场商店无法刷新，设置如下
![20241101040517](https://github.com/user-attachments/assets/8b3ca2da-2d9e-4a3f-89ec-13734539e931)
第一次购买完体力后的游戏界面和软件界面
![20241101040440](https://github.com/user-attachments/assets/ccab8967-4dfc-4ba4-b163-14e48d3fdf70)
![20241101040455](https://github.com/user-attachments/assets/5e875252-5814-480d-b5f1-5a442c77e2e0)
![20241101040500](https://github.com/user-attachments/assets/59cab28e-fb3a-471d-b198-db98c3ef0090)
手动点击刷新后
![20241101040557](https://github.com/user-attachments/assets/df9ebcdd-197d-4de5-823e-01e21582a867)
![20241101040603](https://github.com/user-attachments/assets/8450f55d-9cf2-4c7d-ab63-e44baab3c471)
更换分辨率为1280x720
还是一样的结果
![20241101043255](https://github.com/user-attachments/assets/f959c653-f4f6-48a2-b609-8a0d1f4e2df4)

**Comment by pur1fying** [comment]
已修复 cf19f60
