### ISSUE TITLE
無法開啟baas

### ISSUE THREAD

**Issue by Su6cl3** [pur1fying/blue_archive_auto_script#181]
昨天还可以启动，但是现在的状况是 点BlueArchiveAutoScript.exe 有跳出[命令列介面]、然后自动关掉后GUI没有出现，重开电脑还是一样、baas确定无中文路径，由于没有GUI所以连错误日志都不知道去哪找
![001](https://github.com/user-attachments/assets/01fec51a-3d76-45be-99f1-b652e22ebf86)
是这样吗?   但是我不知道日志在哪边

**Comment by pur1fying** [comment]
在根目录下开启命令行，然后输入bluearchiveautoscript.exe会保留日志

**Comment by steven12240202** [comment]
我也有遇到相同问题，重新下载后依然打不开，换版本也一样

**Comment by waiting0324** [comment]
![image](https://github.com/user-attachments/assets/3e5505d6-1d8d-4139-a936-3aa1effe8c62)
在 11/10 日的一次更新後，我也出現了同樣的問題，
在命令行中有出現 Start app success，但卻未跳出 UI 介面，錯誤日誌中也沒有訊息。

當時發現問題時使用的 Ver 1.1.1，後續重新下載 Ver 1.1.3 版本的 BlueArchiveAutoScript_win_x86_64_Portable_full_env.7z
重新安裝，也無法解決問題。

**Comment by Kiramei** [comment]
稍等，我近期会复现一下这个问题。

**Comment by waiting0324** [comment]
如果有更新到最新版本後還是無法正常開啟 UI 介面的兄弟，
嘗試把自己系統中額外安裝的 Python 移除安裝試試

我原來更新後還是無法正常啟用 UI，
將系統中原來安裝的 Python 移除後，
就能正常呼出 UI 介面了
![image](https://github.com/user-attachments/assets/c22dd8ad-0ded-4999-8a9b-15077aa8517c)

**Comment by pur1fying** [comment]
4312b2fd56784d0fc12f9a14349a51fd3da54afe
问题在于default_config.py中的最下段代码，原因未知

**Comment by Kiramei** [comment]
> 如果有更新到最新版本後還是無法正常開啟 UI 介面的兄弟， 嘗試把自己系統中額外安裝的 Python 移除安裝試試
> 
> 我原來更新後還是無法正常啟用 UI， 將系統中原來安裝的 Python 移除後， 就能正常呼出 UI 介面了 ![image](https://private-user-images.githubusercontent.com/16068120/385396295-c22dd8ad-0ded-4999-8a9b-15077aa8517c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODEzNzQsIm5iZiI6MTczMTU4MTA3NCwicGF0aCI6Ii8xNjA2ODEyMC8zODUzOTYyOTUtYzIyZGQ4YWQtMGRlZC00OTk5LThhOWItMTUwNzdhYTg1MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YzlhNjAzM2U5YjJlY2YyNzlmODI2Yzc3OWVkYTFhNzAzNDZjOWM5NDBiZjc1ZjQyMTg5NmRiMmQ3NjgwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r30BMFbs1k0tz5JprhBXOcU6YsC9pLD8jsJK34UU2vo)

@waiting0324 看起來你的UI分辨率好像不太對，我建議你可以在設置下方的“圖形用戶界面”的配置組中，對於“界面縮放”進行修改，使用“使用系統設置”選項。

**Comment by waiting0324** [comment]
> > 如果有更新到最新版本後還是無法正常開啟 UI 介面的兄弟， 嘗試把自己系統中額外安裝的 Python 移除安裝試試
> > 我原來更新後還是無法正常啟用 UI， 將系統中原來安裝的 Python 移除後， 就能正常呼出 UI 介面了 ![image](https://private-user-images.githubusercontent.com/16068120/385396295-c22dd8ad-0ded-4999-8a9b-15077aa8517c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1ODEzNzQsIm5iZiI6MTczMTU4MTA3NCwicGF0aCI6Ii8xNjA2ODEyMC8zODUzOTYyOTUtYzIyZGQ4YWQtMGRlZC00OTk5LThhOWItMTUwNzdhYTg1MTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDEwNDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YzlhNjAzM2U5YjJlY2YyNzlmODI2Yzc3OWVkYTFhNzAzNDZjOWM5NDBiZjc1ZjQyMTg5NmRiMmQ3NjgwODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.r30BMFbs1k0tz5JprhBXOcU6YsC9pLD8jsJK34UU2vo)
> 
> @waiting0324 看起來你的UI分辨率好像不太對，我建議你可以在設置下方的“圖形用戶界面”的配置組中，對於“界面縮放”進行修改，使用“使用系統設置”選項。

修改後就正常了，謝謝呀~

![image](https://github.com/user-attachments/assets/bd34b805-a9db-4f1f-bd39-5c34f6e403da)
