### ISSUE TITLE
Error changing servers in BAAS

### ISSUE THREAD

**Issue by vRinzler** [pur1fying/blue_archive_auto_script#183]
Hello, it's me reporting a new issue in 1.1.3!
I received the updates through first boot, so I didn't see too many changes in the app. After the -ive ALIVE! event and now the Dragon and Tortoise rerun, I'm having issues with the event not being updated to be automated within BAAS, so I reinstalled the app. Now the original server selected in the script was CN, so I changed it to Global and reboot the script.... for nothing to change. The listed event is still Schale Valentines, the Cafe settings don't have the 2nd Cafe yes/no option, and all Lesson areas are in Chinese. And the app of course fails to recognize the Global client and return an error. Can you take a look into this?
Provided are the images in BAAS that reflect my report. 
Thank you.
![image](https://github.com/user-attachments/assets/0f17e3b5-352e-4888-9d91-9a106ff6fcd2)
![Screenshot 2024-11-14 000454](https://github.com/user-attachments/assets/bbaee4a0-59d1-4cb0-b78e-739090dd3472)
![Screenshot 2024-11-14 000503](https://github.com/user-attachments/assets/804d9723-b50c-4479-967c-e1dc99f299d9)

**Comment by Kiramei** [comment]
Oh，this bug has been recently found but we currently have no idea on it. However, you can temporarily solve this problem following these steps:

1. Open "config/YOUR_CONFIG_DIRECTORY/config.json"

2. Find the "server" config item, change its value to "国际服", like this:

```Json
{
    ...
    "server": "国际服",
    ...
}
```

3. Restart Baas.

We'll go on trying to find the solution concerning this bug.

**Comment by vRinzler** [comment]
I wanted to give some extra update to the situation:
For many reasons, I can't fully toggle off functions like event sweep and hard/normal mission sweep, as well as the update log not showing anything when I click it. Using 1.1.2 and letting it pull updates from the repo is a temporary solution for now, but the server switch bug still remains.

**Comment by Kiramei** [comment]
Er.. I guess it's not the problem of version as the executable file only influence the installer step but never affect the features. While your problems are concerning the UI settings, which may have something to do with i18n, I think. While the Chinese users seem have no such problem,  I wonder if you use the English UI all the time, for I want to know whether it's a problem occurring under other language.

**Comment by vRinzler** [comment]
English is my primary language, so that's what I chose to use all the time. Maybe it is because of language settings? I'll switch to Chinese to check this further.

**Comment by Kiramei** [comment]
Thank you for your response. If I have time, I will check and try to fix the issue.

**Comment by vRinzler** [comment]
After a few days of uninstalling then reinstalling, changing languages,... I can say that both the old and new release of BAAS has the same issue, where I unchecked the tasks I don't need before executing the script, but it still registers those tasks.
Hope the team has free time to take a look at the issues.
Thank you for this great script!

**Comment by pur1fying** [comment]
[config.zip](https://github.com/user-attachments/files/17826882/config.zip)
please try to replace you config folder by unzipping this file, this config has four different servers and may be  enough for temporary use.

**Comment by Kiramei** [comment]
@vRinzler Today, I will get down to fixing the problem. Please give me an ordered list of the problem in that I need to represent it.

**Comment by vRinzler** [comment]
What I'm currently discovering as of 1.1.3:
- Changing servers in settings then reboot the script does not change the dailies settings to reflect it
- Toggling tasks in the task list does not change the config files to match it and remained like default
These 2 requires directly editing the config files of BAAS to be applied when starting the script.
Because Kiramei reported that CN users have no problems, it could be related to the English UI?
