### ISSUE TITLE
BAAS only work in CN SV.

### ISSUE THREAD

**Issue by bigbattle45** [pur1fying/blue_archive_auto_script#186]
I'm not sure what I'm doing wrong but when I launch BAAS in JP and GB it's not working anymore after update.
[Code in CN]
![{0FBE9D97-61B6-493C-8A5E-68634165468C}](https://github.com/user-attachments/assets/68b1e3c7-a25f-430e-b347-2d9fbe4edbd9)

[Code in JP sv.]

![{8AEF7351-2E37-4A7A-9D69-0C673416B6AB}](https://github.com/user-attachments/assets/e67abb0c-78c6-47b4-a840-6af112a3b8ed)
![{9A3428DF-B451-41F2-A2E4-C1B5920BFD72}](https://github.com/user-attachments/assets/c10e9d8c-b4ba-458e-8d57-13fda3585baa)

-/\-

**Comment by pur1fying** [comment]
Your emulator port is incorrect. You should set it in settings.

**Comment by bigbattle45** [comment]
Ah Thanks

**Comment by Kiramei** [comment]
This problem has been fixed in 4a5b7bfafd54959b930d83132985829e8fa94967.
