### ISSUE TITLE
主线图推图问题

### ISSUE THREAD

**Issue by Kiramei** [pur1fying/blue_archive_auto_script#187]
无法推图，十八图，进入下面Panel自动停止。

# Panel:
![image](https://github.com/user-attachments/assets/9dec932b-5379-4b8b-b2f2-95fc5a9278e6)

# Log:
![image](https://github.com/user-attachments/assets/e2add29d-ff55-435f-91e2-ec916ad5e007)

**Comment by Kiramei** [comment]
是不是中间不能有空格，配置配置成"18, 19, 20"无法运行，建议在分割后中间有空格把空格去掉。

**Comment by Kiramei** [comment]
而如果输入"19,20"则运行正常

**Comment by Kiramei** [comment]
还有一个问题，在推图解锁新的章节之后，之前的关卡打完了，这时候直接会跳到新的章节去，用旧的章节去检测新的章节，这时候新的章节没有完成就会进去，然后用旧的章节的脚本去刷就会出问题。

**Comment by Kiramei** [comment]
新的问题，章节切换的时候，会自动切换新图，但是脚本依旧拿着旧图的方法去打

**Comment by pur1fying** [comment]
> 配置配置成"18, 19, 20"，或者是“18,19,20”，无法运行。

fixed at 0374fab961f9faea3ad1eac9a8842906e1d349b6 
</b>
And we can test input data and expected output with develop_tools/test_explore_task_data.py
More test examples will be added.
