### ISSUE TITLE
建议在自述文件中添加关于Qt相关的帮助面板

### ISSUE THREAD

**Issue by SCMECYDYSY** [pur1fying/blue_archive_auto_script#188]
如题，尽管baas用的人不多（划掉）但是安装过程中总会有些小白遇到Qt环境配置和冲突的问题，建议加上

经测试baas兼容多个版本的Qt，但是打不开一定是没有配置好环境变量
![image](https://github.com/user-attachments/assets/95dcdb50-aff7-46b5-b4f9-c8b8546b4b3e)

此电脑→高级系统设置→高级→环境变量
![image](https://github.com/user-attachments/assets/18279225-d997-46e0-bb5a-c4f1295fcfb8)
新建一个
变量名 QT_QPA_PLATFORM_PLUGIN_PATH
变量值  填写已知兼容的qt目录
MUMU模拟器与其他的Qt5不兼容，非必要不建议填写自己安装的Qt（要用到时自己改），但是MUMU的Qt与Baas兼容
Baas的qt目录：（Baas的安装目录）\BlueArchiveAutoSctipt\env\Lib\site-packages\PyQt5\Qt5\plugins
MuMu的qt目录：（MuMu模拟器安装目录）\MuMu Player 12\shell\plugins
自己装的qt：自己研究，在py的目录下，微软商店装的py在AppData\Local里

Baas打不开的问题主要是需要手动添加变量，变量值填上面的都行，MuMu模拟器可能会和自己装的和Bass目录中的qt冲突，需要填写MuMu的路径或者删掉变量……

**Comment by Kiramei** [comment]
你可以尝试加个PR

**Comment by SCMECYDYSY** [comment]
> 你可以尝试加个PR

已提交
