### ISSUE TITLE
跪求国际服支持

### ISSUE THREAD

**Issue by Egolas** [pur1fying/blue_archive_auto_script#21]
RT

**Comment by pur1fying** [comment]
在写了

**Comment by CNCoreSteb** [comment]
再求个日服Thanks♪(･ω･)ﾉ

**Comment by RedDeadDepresso** [comment]
Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.

**Comment by RedDeadDepresso** [comment]
@CNCoreSteb, if you are looking for Japanese server, you can try [ArisuAutoSweeper](https://github.com/TheFunny/ArisuAutoSweeper). It's still in development but looks promising.

**Comment by pur1fying** [comment]
@RedDeadDepresso You are doing a really great work！

**Comment by RedDeadDepresso** [comment]
> @RedDeadDepresso You are doing a really great work！

Hi, thanks for the compliment. It was my first project and it turned out to be better than expected, however, I don't have the time or skill required to continue on BAAuto so feel free to use the source code or ideas. 

Also, I made some Github issues where I explain in details BAAuto. 

https://github.com/MaaAssistantArknights/MBA/issues/10

https://github.com/TheFunny/ArisuAutoSweeper/issues/1

**Comment by pur1fying** [comment]
> > @RedDeadDepresso You are doing a really great work！
> 
> Hi, thanks for the compliment. It was my first project and it turned out to be better than expected, however, I don't have the time or skill required to continue on BAAuto so feel free to use the source code or ideas.
> 
> Also, I made some Github issues where I explain in details BAAuto.
> 
> [MaaAssistantArknights/MBA#10](https://github.com/MaaAssistantArknights/MBA/issues/10)
> 
> [TheFunny/ArisuAutoSweeper#1](https://github.com/TheFunny/ArisuAutoSweeper/issues/1)

ok,I will read them when I am spared，thank you for your devotion

**Comment by Ateee329** [comment]
> Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.

This helped me a lot! Thanks!!

**Comment by RedDeadDepresso** [comment]
> > Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.
> 
> This helped me a lot! Thanks!!

I'm glad that it was helpful. May I ask how accurate the student names in traditional Chinese are? I tried to web scrape them from https://ba.gamekee.com/, the only website I found with names in traditional Chinese. If they are not accurate, I would appreciate if you could provide another website.

**Comment by halfyua** [comment]
> > > Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.
> > 
> > 
> > This helped me a lot! Thanks!!
> 
> I'm glad that it was helpful. May I ask how accurate the student names in traditional Chinese are? I tried to web scrape them from https://ba.gamekee.com/, the only website I found with names in traditional Chinese. If they are not accurate, I would appreciate if you could provide another website.

https://forum.gamer.com.tw/C.php?bsn=38898&snA=698
Maybe this website can help you.

**Comment by Ateee329** [comment]
> > > Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.
> > 
> > 
> > This helped me a lot! Thanks!!
> 
> I'm glad that it was helpful. May I ask how accurate the student names in traditional Chinese are? I tried to web scrape them from https://ba.gamekee.com/, the only website I found with names in traditional Chinese. If they are not accurate, I would appreciate if you could provide another website.

The website you just sent has only Simplified Chinese. I just found this website https://zh.moegirl.org.cn/zh-hant/蔚蓝档案#.E7.99.BB.E5.9C.BA.E8.A7.92.E8.89.B2.E4.B8.8E.E5.A3.B0.E4.BC.98, but they don’t have picture of each corresponding student. I hope this helps you.

**Comment by Kiramei** [comment]
> > > > Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.
> > > 
> > > 
> > > This helped me a lot! Thanks!!
> > 
> > 
> > I'm glad that it was helpful. May I ask how accurate the student names in traditional Chinese are? I tried to web scrape them from https://ba.gamekee.com/, the only website I found with names in traditional Chinese. If they are not accurate, I would appreciate if you could provide another website.
> 
> The website you just sent has only Simplified Chinese. I just found this website [https://zh.moegirl.org.cn/zh-hant/蔚蓝档案#.E7.99.BB.E5.9C.BA.E8.A7.92.E8.89.B2.E4.B8.8E.E5.A3.B0.E4.BC.98](https://zh.moegirl.org.cn/zh-hant/%E8%94%9A%E8%93%9D%E6%A1%A3%E6%A1%88#.E7.99.BB.E5.9C.BA.E8.A7.92.E8.89.B2.E4.B8.8E.E5.A3.B0.E4.BC.98), but they don’t have picture of each corresponding student. I hope this could help you.

I've viewed the website you've provided. For convenience, a spider to grab the students' names can be put into consideration. If there're some students' pics, I'd appreciate. Thanks, bro

**Comment by Ateee329** [comment]
> > > > > Hi @Egolas . I translated your problems using Google Translate, but if you are looking for a Blue Archive script for global, I created one called [BAAuto](https://github.com/RedDeadDepresso/BAAuto). It's a little unoptimised and slow, but it will get the job done while pur1fying is working on adapting baas.
> > > > 
> > > > 
> > > > This helped me a lot! Thanks!!
> > > 
> > > 
> > > I'm glad that it was helpful. May I ask how accurate the student names in traditional Chinese are? I tried to web scrape them from https://ba.gamekee.com/, the only website I found with names in traditional Chinese. If they are not accurate, I would appreciate if you could provide another website.
> > 
> > 
> > The website you just sent has only Simplified Chinese. I just found this website [https://zh.moegirl.org.cn/zh-hant/蔚蓝档案#.E7.99.BB.E5.9C.BA.E8.A7.92.E8.89.B2.E4.B8.8E.E5.A3.B0.E4.BC.98](https://zh.moegirl.org.cn/zh-hant/%E8%94%9A%E8%93%9D%E6%A1%A3%E6%A1%88#.E7.99.BB.E5.9C.BA.E8.A7.92.E8.89.B2.E4.B8.8E.E5.A3.B0.E4.BC.98), but they don’t have picture of each corresponding student. I hope this could help you.
> 
> I've viewed the website you've provided. For convenience, a spider to grab the students' names can be put into consideration. If there're some students' pics, I'd appreciate. Thanks, bro

Unfortunately I couldn't find any, most of them are in Simplified Chinese. The one sent by @halfyua might help you.

**Comment by xurunyu** [comment]
@RedDeadDepresso   @Ate329 
Hi, I found a web site https://schale.gg/?chara=Aru  
You can change the language with the bottom at the up right corner.
I hope this helps.
<img width="1335" alt="image" src="https://github.com/pur1fying/blue_archive_auto_script/assets/3078255/8c7058a1-737d-4980-83af-c2594f7a24c6">

**Comment by Kiramei** [comment]
We have partly reconstructed the project while purifying has coded and supported the global server version.

**Comment by pur1fying** [comment]
国际服已经适配

**Comment by Ate329** [comment]
幸苦了！
