### ISSUE TITLE
怎么使用呀？

### ISSUE THREAD

**Issue by AnRamRan** [pur1fying/blue_archive_auto_script#3]
可以做成exe程序吗？这样的话还方便一些

**Comment by pur1fying** [comment]
再过一周左右时间吧 ， exe在做了，后续会附上使用文档

**Comment by Kiramei** [comment]
UI界面锐意开发中～

**Comment by Jamesgender** [comment]
期待！顺便问一句这个是模拟器上用的吗

**Comment by Kiramei** [comment]
> 期待！顺便问一句这个是模拟器上用的吗

这个不是安卓软件，是windows上的应用，就是你一边开模拟器一边开这个

**Comment by Jamesgender** [comment]
知道了，感谢大佬

**Comment by pur1fying** [comment]
最近做ui的人有点忙，可能要再等一会啦qwq

**Comment by AnRamRan** [comment]
QWQ

**Comment by AnRamRan** [comment]
希望UI像mma一样简洁

**Comment by zhuYuanSou** [comment]
表示强烈期待，最近每天都在来看做出来没

**Comment by AnRamRan** [comment]
+1

**Comment by AnRamRan** [comment]
+1

**Comment by AnRamRan** [comment]
+1

**Comment by AnRamRan** [comment]
+1

**Comment by hijack114514** [comment]
就是我提个建议，如果gui实在制作困难的话可以找alas组商量一下，看下是否可以用alas调用接口，人气起来才有更多人contribute（笑）

**Comment by pur1fying** [comment]
国庆肯定写完，qwq

**Comment by kerstker** [comment]
十万甚至九万个问题，OCR的环境问题好多，甚至没能运行起来（气晕

**Comment by AnRamRan** [comment]
QWQ

**Comment by AnRamRan** [comment]
02

**Comment by AnRamRan** [comment]
好了吗

**Comment by pur1fying** [comment]
> 好了吗

还有一些bug调一下

**Comment by AnRamRan** [comment]
QWQ

**Comment by AnRamRan** [comment]
好了吗

**Comment by AnRamRan** [comment]
好了吗??????????????????????????????????

**Comment by zhuYuanSou** [comment]
作者们加油啊加油

**Comment by AnRamRan** [comment]
加油加油加油加油

**Comment by misaka10843** [comment]
感觉打包出来的话还是建议打包个python，不然的话非多线程+无法设置代理的话还是下不动的（可以参考alas）
（在设置代理（非网卡/TUN模式下）py请求如果不添加代理设置都是会报错的）
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/69132853/a800f373-fc7f-4c06-bbb6-390aecb29af7)

而且在用户端已经有了python的情况下还是检测到没有安装（估计是版本不同的原因）

**Comment by AnRamRan** [comment]
QWQ

**Comment by AnRamRan** [comment]
加油

**Comment by pur1fying** [comment]
> 感觉打包出来的话还是建议打包个python，不然的话非多线程+无法设置代理的话还是下不动的（可以参考alas） （在设置代理（非网卡/TUN模式下）py请求如果不添加代理设置都是会报错的） ![image](https://user-images.githubusercontent.com/69132853/273235099-a800f373-fc7f-4c06-bbb6-390aecb29af7.png)
> 
> 而且在用户端已经有了python的情况下还是检测到没有安装（估计是版本不同的原因）
> 
> 然后就是依赖的话似乎还需要安装VSBTool，不然会编译失败（Polygon3似乎没有3.9+的whl） ![image](https://user-images.githubusercontent.com/69132853/273238337-5d90732c-67ba-4963-b8ae-829881a6b91e.png)

如果有python建议直接用现成的环境装requirements，装好后运行window.py。初次启动会在当前目录下装一个python虚拟环境(已使用多进程)，开代理会比较快

**Comment by pur1fying** [comment]
后续会优化安装问题

**Comment by AnRamRan** [comment]
可以参考一下maa

**Comment by misaka10843** [comment]
> > 感觉打包出来的话还是建议打包个python，不然的话非多线程+无法设置代理的话还是下不动的（可以参考alas） （在设置代理（非网卡/TUN模式下）py请求如果不添加代理设置都是会报错的） ![image](https://user-images.githubusercontent.com/69132853/273235099-a800f373-fc7f-4c06-bbb6-390aecb29af7.png)
> > 而且在用户端已经有了python的情况下还是检测到没有安装（估计是版本不同的原因）
> > 然后就是依赖的话似乎还需要安装VSBTool，不然会编译失败（Polygon3似乎没有3.9+的whl） ![image](https://user-images.githubusercontent.com/69132853/273238337-5d90732c-67ba-4963-b8ae-829881a6b91e.png)
> 
> 如果有python建议直接用现成的环境装requirements，装好后运行window.py。初次启动会在当前目录下装一个python虚拟环境(已使用多进程)，开代理会比较快

用venv创建虚拟环境后启动的话还是会出现问题
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/69132853/a0f9a969-bd26-4fa1-b386-2ba50e1dde24)

```log
QLayout: Attempting to add QLayout "" to HomeFragment "", which already has a layout
```
