### ISSUE TITLE
添加文档网站到About中

### ISSUE THREAD

**Issue by lzw-723** [pur1fying/blue_archive_auto_script#32]
如果Github Pages部署成功，可以直接添加项目说明上
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/42259168/86e6b5ea-6f53-4138-920a-ce8c601ba661)

效果
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/42259168/8003a9fe-da20-416a-950e-9d3aa7286eb1)

**Comment by pur1fying** [comment]
加了

**Comment by lzw-723** [comment]
虽然但是
如果正确部署了，那么应该是http://pur1fying.github.io/blue_archive_auto_script

而
https://blog.lzwi.fun/blue_archive_auto_script/是我在fork的测试环境

一定要在仓库的设置中为gh-pages分支开启github pages

:-)
