### ISSUE TITLE
让分辨率不为1280*720的设备用adb转为该分辨率运行

### ISSUE THREAD

**Issue by MCOTF** [pur1fying/blue_archive_auto_script#33]
没下模拟器，在手机用adb更改完分辨率后，无论怎么运行baas都会将该设备视为原生分辨率，感觉可以加一个更改分辨率的选项，或者强制执行

**Comment by pur1fying** [comment]
可以试试，目前还未在手机上实测过

**Comment by Daodanfd5** [comment]
> 没下模拟器，在手机用adb更改完分辨率后，无论怎么运行baas都会将该设备视为原生分辨率，感觉可以加一个更改分辨率的选项，或者强制执行

 某些设备拒绝修改分辨率，尤其是蓝叠模拟器5

**Comment by MCOTF** [comment]
我的手机已经root了，而且降分辨率后一眼就能看出来画面差别👀
不过改分辨率这一块我是用adb指令改的，难道是这种方法不行吗

**Comment by MCOTF** [comment]
> > 没下模拟器，在手机用adb更改完分辨率后，无论怎么运行baas都会将该设备视为原生分辨率，感觉可以加一个更改分辨率的选项，或者强制执行
> 
>  某些设备拒绝修改分辨率，尤其是蓝叠模拟器5

我的手机已经root了，而且降分辨率后一眼就能看出来画面差别👀
不过改分辨率这一块我是用adb指令改的，难道是这种方法不行吗

**Comment by Daodanfd5** [comment]
> > > 没下模拟器，在手机用adb更改完分辨率后，无论怎么运行baas都会将该设备视为原生分辨率，感觉可以加一个更改分辨率的选项，或者强制执行
> > 
> >  某些设备拒绝修改分辨率，尤其是蓝叠模拟器5
> 
> 我的手机已经root了，而且降分辨率后一眼就能看出来画面差别👀
> 不过改分辨率这一块我是用adb指令改的，难道是这种方法不行吗

是的 我用蓝叠的Android 9和Android 11 它们都拒绝修改分辨率，会修改失败

**Comment by pur1fying** [comment]
已经支持16：9更高分辨率的画质
