### ISSUE TITLE
进去游戏主界面后反复点击右上角，不执行任何任务

### ISSUE THREAD

**Issue by autumn-moon-py** [pur1fying/blue_archive_auto_script#35]
程序版本1.1.1，依赖安装正常，脚本路径确定纯英文，模拟器连接正常，模拟器分辨率为1280x720
[error.log](https://github.com/pur1fying/blue_archive_auto_script/files/13697135/error.log)
[output.log](https://github.com/pur1fying/blue_archive_auto_script/files/13697132/output.log)

https://github.com/pur1fying/blue_archive_auto_script/assets/77103327/213db667-6c67-4f9d-aff5-619b49e37cea

**Comment by ACBAD** [comment]
哥们，我发现一个问题。baas用的是uiautomator2库里的screenshot方法截图，但是我单独把这个截的图拿出来导出到电脑里的时候发现这个截图只能截到主界面，我再测试发现关掉ATX的uiautomator服务可以解决，但是点击功能就不行了，你可以看看是不是这个问题
<img width="374" alt="Baas_issue1" src="https://github.com/pur1fying/blue_archive_auto_script/assets/53413065/86a350e7-fa05-476c-8f57-147ab1701ae6">
<img width="365" alt="Baas_issue2" src="https://github.com/pur1fying/blue_archive_auto_script/assets/53413065/264251b4-fa50-4ad8-b4bd-d69da0f7001b">
<img width="339" alt="Baas_issue3" src="https://github.com/pur1fying/blue_archive_auto_script/assets/53413065/8dbb80ca-3c83-4c3e-b578-3a9ebad816e3">

**Comment by pur1fying** [comment]
@ACBAD @autumn-moon-py 需要把mumu模拟器的后台保活关闭

**Comment by ACBAD** [comment]
> @ACBAD @autumn-moon-py 需要把mumu模拟器的后台保活关闭

谢谢，已解决
