### ISSUE TITLE
设置竞技场顺序导致崩溃

### ISSUE THREAD

**Issue by ACBAD** [pur1fying/blue_archive_auto_script#36]
## 问题描述

 在设置竞技场顺序时，输入数据点击确定后崩溃

## 重现步骤

进入GUI调度设置
找到竞技场设置栏点开
在输入框输入顺序（如1234）

https://github.com/pur1fying/blue_archive_auto_script/assets/53413065/a9094a9e-4836-4133-9723-d5043300c503

## 附加信息

我看了errror.log和output.log发现都没有报错，于是用终端跑了一下发现以下报错
```
Traceback (most recent call last):
  File "D:\CodeLib\Download\Baas\gui\components\expand\arenaPriority.py", line 36, in __accept
    self.priority_list = [int(x) for x in changed_text]
TypeError: 'bool' object is not iterable
```
没学过python，问了下gpt说第25行`self.accept.clicked.connect(self.__accept)`这句改成`self.accept.clicked.connect(self.__accept_from_input)`即可，试验过后确实可以修复

## 环境信息

Python：Baas自带venv
模拟器：mumu12
操作系统：Windows11
网络环境：正常

以上个人意见，希望能帮助开发

**Comment by pur1fying** [comment]
@Kiramei 有关ui的问题可以参考一下

**Comment by ACBAD** [comment]
> 首先感谢反馈问题，可以先不用管那个顺序，整个baas都在重构中，预计这周会更新TAT

好，大佬加油

**Comment by Kiramei** [comment]
该功能目前已经移除并进行了替换。
