### ISSUE TITLE
MUMU模拟器启动提示device agent responds with an error code 503

### ISSUE THREAD

**Issue by oyidi** [pur1fying/blue_archive_auto_script#50]
INFO | 2024-01-03 11:01:19.188451 | Starting Blue Archive Auto Script... 
    INFO | 2024-01-03 11:01:19.188451 | --------Initialing All Data---------- 
    INFO | 2024-01-03 11:01:19.188451 | Start Reading Config 
    INFO | 2024-01-03 11:01:19.189429 | SUCCESS 
    INFO | 2024-01-03 11:01:19.189429 | Start Detecting Server 
    INFO | 2024-01-03 11:01:19.189429 | Current Server: Global 
    INFO | 2024-01-03 11:01:19.190407 | Start initializing OCR 
    INFO | 2024-01-03 11:01:19.191382 | Start initializing rgb_feature 
    INFO | 2024-01-03 11:01:19.206041 | Successfully initialized rgb_feature 
    INFO | 2024-01-03 11:01:19.325606 | Start initializing image data 
    INFO | 2024-01-03 11:01:19.326585 | --------------Init Emulator---------------- 
    INFO | 2024-01-03 11:01:19.326585 | adb port: 16384 
    INFO | 2024-01-03 11:01:19.478797 | Test ocrEN : I love Aris 
    INFO | 2024-01-03 11:01:19.673814 | Image data successfully initialized total assets : 17 
    INFO | 2024-01-03 11:01:19.681629 | Test ocrNUM : 0001011001001100100101101010011010 
    INFO | 2024-01-03 11:01:19.681629 | OCR initialization concluded 
   ERROR | 2024-01-03 11:01:20.231341 | ('device agent responds with an error code 503', '') 
   ERROR | 2024-01-03 11:01:20.232319 | Emulator initialization failed 
CRITICAL | 2024-01-03 11:01:20.232319 | Initialization Failed 
    INFO | 2024-01-03 11:01:20.232319 | --------Initialing All Data---------- 
    INFO | 2024-01-03 11:01:20.232319 | Start Reading Config 
    INFO | 2024-01-03 11:01:20.233296 | SUCCESS 
    INFO | 2024-01-03 11:01:20.233296 | Start Detecting Server 
    INFO | 2024-01-03 11:01:20.233296 | Current Server: Global 
    INFO | 2024-01-03 11:01:20.233296 | Start initializing OCR 
    INFO | 2024-01-03 11:01:20.234274 | OCR initialization concluded 
    INFO | 2024-01-03 11:01:20.234274 | Start initializing rgb_feature 
    INFO | 2024-01-03 11:01:20.235249 | Successfully initialized rgb_feature 
    INFO | 2024-01-03 11:01:20.235249 | Start initializing image data 
    INFO | 2024-01-03 11:01:20.235249 | --------------Init Emulator---------------- 
    INFO | 2024-01-03 11:01:20.235249 | adb port: 16384 
    INFO | 2024-01-03 11:01:20.240137 | Image data successfully initialized total assets : 17 
   ERROR | 2024-01-03 11:01:21.069382 | ('device agent responds with an error code 503', '') 
   ERROR | 2024-01-03 11:01:21.069382 | Emulator initialization failed 
CRITICAL | 2024-01-03 11:01:21.069382 | Initialization Failed 
CRITICAL | 2024-01-03 11:01:21.069382 | 
---------------------------------------------------------------------------------------------- 
    INFO | 2024-01-03 11:01:21.069382 | start activities 
    INFO | 2024-01-03 11:01:21.094786 | error occurred, stop all activities 
   ERROR | 2024-01-03 11:01:21.095763 | 'NoneType' object has no attribute 'heartbeat' 
端口号检查过是正确的，adb工具输入adb -s 127.0.0.1:16384 shell ls也能正常显示

**Comment by pur1fying** [comment]
进qq群我帮你看看？这个bug我还是第一次见

**Comment by Kiramei** [comment]
你可以在CMD中尝试下面代码：
```Shell 
curl 127.0.0.1:16384
```
