### ISSUE TITLE
GUI : English support 

### ISSUE THREAD

**Issue by ChikyuTenshi** [pur1fying/blue_archive_auto_script#51]
Is English GUI support planned any time soon? I know Global was supported recently but I can't setup my settings properly because of the language barrier

**Comment by Kiramei** [comment]
Ok, I'll try to support it in the future

**Comment by Kiramei** [comment]
I have to prepared for the final test this term. 
I'll consider it when I finish my test.

**Comment by RedDeadDepresso** [comment]
@ChikyuTenshi If you are still struggling, you can download the dev branch of my ArisuAutoSweeper fork as a zip. It has most of the daily tasks, it is completely English and supports Global.

Here are the instructions:

1. Download https://github.com/RedDeadDepresso/ArisuAutoSweeper/tree/dev as zip and extract 
2. Type pip install -r requirements-in.txt in cmd
3. Open gui.py
4. Type and enter http://127.0.0.1:23467/ into your browser
5. Change the game server and game text language to OVERSEA-GLOBAL and English respectively in the AAS Settings, set everything else to your liking and then click Start.

I thought pur1fying would only support the traditional Chinese version of global and the repo was inactive for a while before December. In the end, I implemented most of the dailies for the sake of completion.

**Comment by pur1fying** [comment]
@RedDeadDepresso Actually global version only supports English as the ocr model for English is very precise

**Comment by RedDeadDepresso** [comment]
I know. It was unexpected since the other blue archive scripts I found before your implementation of Global only featured Traditional Chinese.

**Comment by ChikyuTenshi** [comment]
@Kiramei You can take your time until you're done with your exams, Thank you for considering it :)

@RedDeadDepresso I'm sorta struggling with all of that, Do you mind if I start a new issue in the original Github and tag you in it?

**Comment by RedDeadDepresso** [comment]
@ChikyuTenshi Sure, go ahead.

**Comment by Kiramei** [comment]
Thanks @RedDeadDepresso , we've now support multi-language
