### ISSUE TITLE
初步使用的一些问题

### ISSUE THREAD

**Issue by GreyQAQ** [pur1fying/blue_archive_auto_script#60]
1、闪退：
普通推图多设置就会闪退（如输入“19，20，21”）、
另外很多时候都会直接闪退

2、国际服适配：
国际服是否可适配繁体中文？（下面遇到的问题均在设置英文界面时出现）
并且活动推图是否可适配国际服？现在活动推图貌似是国服的进度

3、推图
设置推普通图，会直接显示推图完成然后退出……与设置的图数字无关
（WARNING | 2024-02-02 16:50:53.474362 | Region not support ）
设置推困难图目前有两个问题：
（1）选用自己没有设置的队伍序号，普通里设置了神秘队伍两个都是1，但是去4队找
（2）格子选中问题：走格子时只会点一下，经常点歪后没反应卡死在原地，无后续操作

4、日程
点进日程页面直接报错停止了，只能不安排这个任务
（ERROR | 2024-02-02 16:47:27.640199 | invalid literal for int() with base 10: '' 
   ERROR | 2024-02-02 16:47:27.640199 | invalid literal for int() with base 10: '' 
   ERROR | 2024-02-02 16:47:27.640199 | error occurred, stop all activities 
    INFO | 2024-02-02 16:47:28.004219 | error occurred, stop all activities 
   ERROR | 2024-02-02 16:47:28.004219 | 'bool' object is not subscriptable ）

5、点击逻辑
很多地方只会点一次，遇到没见过的弹窗就不动
比如竞技场内战胜高排名对手，排名更新后会给石头的页面直接卡死

6、每日清体力
可否不设置次数，而是选择在某个副本清空体力？国际服和日服貌似有直接最大次数的选项

暂时发现或想起这些问题，麻烦大佬了！
辛苦辛苦！

**Comment by pur1fying** [comment]
1.
普通和困难推图目前只到17，新版本(由于ui作者有事还未更新)才添加到24图，闪退问题会好好修复。
2.
(1). 繁中以后可能会写,使用英文的最初原因是因为英文ocr十分准确
(2). 活动推图有空余时间做三服适配(学生党，可能不会每个服务器每个活动都有时间写)
3.
(1)推图数据及点击位置坐标收录时是按照主队编号(打boss队)小于副队，所以用户使用时也必须主队编号小于副队(否则点击位置坐标会发生偏移)所以出现。
(2)推图点击只会做一次(因为不知道怎么判断到底有没有点到(即队伍有没有移动)，如果有好的方法可以告诉我添加适配)，没点到的原因也可以说一下，因为每一关我至少测试过一次能完全自动打完关卡。
4.
日程这个已经遇到过了是因为日程券是两位数导致后面的数组超出了设定范围(新版本已经修复)。
5.
遇到没见过的弹窗可以将图片(1280x720)原图发给我添加适配(目前我只有一个国际服和日服的号有些图片一直没遇到)。
6.
设置最大次数选项是有写这个逻辑的，但是ui暂时没更新,所以暂时没法设置。

新版本会尽量快点更新的，感谢反馈问题

**Comment by pur1fying** [comment]
新版本已发布，已修复问题
