### ISSUE TITLE
如果你在安装时发现this application failed to start because no Qt，请确保你的路径中没有英文

### ISSUE THREAD

**Issue by cjc9812** [pur1fying/blue_archive_auto_script#71]
隔壁alas框架支持中文路径就没注意；
修了三小时重装了五遍pyqt5突发奇想好像这俩框架不一样来着；
五秒进UI；
因为过于悲伤建议开发者在readme里面提一嘴；

**Comment by pur1fying** [comment]
已添加，抱歉（，这个问题只在b站的常见问题详解里提了一嘴
