### ISSUE TITLE
MomoTalk在`2560 * 1440`下无法点击对话时的回复

### ISSUE THREAD

**Issue by Parsifa1** [pur1fying/blue_archive_auto_script#72]
如图，这种回复框无法点击，可能是比例问题
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/31800073/b52e39b9-d513-4bba-bba4-7a6ebc93c397)
~~本来想试着pr一下发现不知道怎么定位点击的位置（~~

**Comment by pur1fying** [comment]
再试一下看看？

**Comment by pur1fying** [comment]
这里是检测蓝色竖条像素位置的，但是调试发现2560*1440 分辨率下像素位置偏移了1....

**Comment by Parsifa1** [comment]
谢谢！
