### ISSUE TITLE
[Bug] 活动剧情推故事刷新循环Bug

### ISSUE THREAD

**Issue by SummonHIM** [pur1fying/blue_archive_auto_script#74]
刷活动图推故事的功能无法正确识别有战斗的地图。导致在切换任务页面刷新时卡住。会持续点击`click (1027 , 87 ) `

**Comment by pur1fying** [comment]
已确定问题出在 ui 跳过故事 -> 编队界面时 短暂出现活动主页界面被截图，已做修复

**Comment by SummonHIM** [comment]
> 已确定问题出在 ui 跳过故事 -> 编队界面时 短暂出现活动主页界面被截图，已做修复

谢谢修复
