### ISSUE TITLE
国服悬赏、学院交流无法自动选择列表第一位

### ISSUE THREAD

**Issue by DongGuaGH** [pur1fying/blue_archive_auto_script#75]
Current Server: CN 
screenshot_interval set to 0.3 
adb port: 16384 
Screen Size (1920, 1080) 
Screen Size Ratio: 1.5 

脚本莫名其妙的在选择第一关的时候选择了第三关，导致最终跳过了第一关的扫荡

> INFO | 2024-03-08 11:51:54.328296 | Start scrimmage task: Trinity count : 5 
    INFO | 2024-03-08 11:51:54.328296 | find : main_page 
    INFO | 2024-03-08 11:51:54.329309 | click (1198 , 580) 
    INFO | 2024-03-08 11:51:55.183380 | find main_page_home-feature 
    INFO | 2024-03-08 11:51:55.184399 | click (1198 , 580) 
    INFO | 2024-03-08 11:51:57.106310 | find main_page_bus 
    INFO | 2024-03-08 11:51:57.107344 | click (716 , 599) 
    INFO | 2024-03-08 11:51:58.145759 | find main_page_bus 
    INFO | 2024-03-08 11:51:58.148260 | click (716 , 599) 
    INFO | 2024-03-08 11:51:58.972962 | find scrimmage_academy-select 
    INFO | 2024-03-08 11:51:58.973967 | click (992 , 280) 
    INFO | 2024-03-08 11:51:59.799198 | end : scrimmage_level-list 
    INFO | 2024-03-08 11:51:59.801391 | find scrimmage_level-list 
    INFO | 2024-03-08 11:51:59.802393 | click (1118 , 380) 
    INFO | 2024-03-08 11:52:00.962402 | end : scrimmage_task-info 
    INFO | 2024-03-08 11:52:00.963379 | click (1014 , 300) 4 times 
    INFO | 2024-03-08 11:52:05.502940 | find scrimmage_task-info 
    INFO | 2024-03-08 11:52:05.504222 | click (932 , 408) 
    INFO | 2024-03-08 11:52:06.413713 | end : scrimmage_purchase-scrimmage-ticket 
 WARNING | 2024-03-08 11:52:06.413713 | INADEQUATE TICKET 
    INFO | 2024-03-08 11:52:06.413713 | Finish scrimmage task: Trinity 

![扫荡](https://github.com/pur1fying/blue_archive_auto_script/assets/26429772/ceb15621-0322-40bd-9e48-7ca5e878e155)
![选择学院](https://github.com/pur1fying/blue_archive_auto_script/assets/26429772/dcb1d464-7a98-4e4e-a070-cd8f1bea4562)

**Comment by pur1fying** [comment]
已修复，后续可以再测试一下
