### ISSUE TITLE
waiting状态下定时清体；困难，简单清体模块先后顺序自定义

### ISSUE THREAD

**Issue by heidon-sensei** [pur1fying/blue_archive_auto_script#76]
1 定时清体（主诉求）
要刷的关卡编号复制到一个变量a里，完成的放在另一个变量b里，然后用户设定在waiting状态下，过x分钟检查一次未完成的关卡（或者在主页面截取并识别体力数值，用户设定在某一个值x时进行清体），再执行刷图任务；重启的时候自动清空ab变量并重新将预设队列复制进变量a。
2 困难关卡清体与简单关卡清体模块自定义先后顺序（附加诉求）
在困难关卡清体模块的配置页面增加选项框“优先刷取困难关卡”，让用户合理可以安排多余体力

拒绝体力浪费，从我做起

**Comment by Kiramei** [comment]
可以看看新版调度器详细配置中的设置能否满足你的需求。

**Comment by heidon-sensei** [comment]
> 可以看看新版调度器详细配置中的设置能否满足你的需求。

其实把间隔时间**### 改成设定时间节点**（不是重置任务，类似于闹钟那样），到某个时间节点时将任务加入任务栏可能会更好。不过如果重置任务不是将当前运行记录清空的话建议标明

**Comment by heidon-sensei** [comment]
> 可以看看新版调度器详细配置中的设置能否满足你的需求。

清空体力这两项尽量合并一下吧（调度），目标是实现完全刷完hd的任务才刷normal，或者编号改为hd：H1-2-3表示hd的1-2关卡刷3次，normal：1-3-5表示normal的1-3关卡刷5次

此外，hd关卡似乎没加这个
![K`ZHYXO0AR8G~U)R2% $FQV](https://github.com/pur1fying/blue_archive_auto_script/assets/162718826/61c7b5f0-de53-4c9f-bbaa-013f3c55d43d)
