### ISSUE TITLE
Request To Update the documentation

### ISSUE THREAD

**Issue by Kiramei** [pur1fying/blue_archive_auto_script#77]
@lzw-723 Hello, bro, I wonder if you could update the documentation of the project? 
I'd like to know how you construct the page if you don't have spare time to update it.

**Comment by lzw-723** [comment]
I'm happy to update the documentation, but only if it should be properly hosted in this repository and not my fork :)
https://github.com/pur1fying/blue_archive_auto_script/pull/31#issue-2000748430

**Comment by Kiramei** [comment]
> I'm happy to update the documentation, but only if it should be properly hosted in this repository and not my fork :)
> https://github.com/pur1fying/blue_archive_auto_script/pull/31#issue-2000748430

I suppose that you can commit a pull request and we'll accept it after consideration.

**Comment by pur1fying** [comment]
@lzw-723 I‘ve invited you to be a collaborator of the repository.

**Comment by lzw-723** [comment]
> @lzw-723 I‘ve invited you to be a collaborator of the repository.

It's fine.

**Comment by lzw-723** [comment]
@pur1fying If you can, please turn on the GitHub pages feature for this repository so that the documentation can be deployed and accessed correctly!

https://github.com/pur1fying/blue_archive_auto_script/settings/pages

**Comment by lzw-723** [comment]
> @pur1fying If you can, please turn on the GitHub pages feature for this repository so that the documentation can be deployed and accessed correctly!
> 
> https://github.com/pur1fying/blue_archive_auto_script/settings/pages

![image](https://github.com/pur1fying/blue_archive_auto_script/assets/42259168/6ad7bfb5-c45e-4103-9f40-66de7bb14433)

**Comment by lzw-723** [comment]
Maybe only the owner has access to it.

**Comment by pur1fying** [comment]
@lzw-723 Is this ok？
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/0a9a19cb-6da0-4a7c-98a1-5a75e266666c)

**Comment by lzw-723** [comment]
> @lzw-723 Is this ok？
> ![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/0a9a19cb-6da0-4a7c-98a1-5a75e266666c)
> 

Yes, it's working!

Looks good: https://pur1fying.github.io/blue_archive_auto_script/

**Comment by pur1fying** [comment]
@lzw-723 OK. And I’m wondering if I want to edit the content in the pages，is it right to change the htmls in the "gh-pages" branch，the documents need to be updated.

**Comment by lzw-723** [comment]
> @lzw-723 OK. And I’m wondering if I want to edit the content in the pages，is it right to change the htmls in the "gh-pages" branch，the documents need to be updated.

**Do not edit any files in the gh-pages branch directly!**

***

This document is built using [vitepress](https://vitepress.dev/zh/guide/getting-started), you can use it well if you know markdown.
`Relax and try changing the md file in the docs directory, don't forget the **.vitepress/config.mjs** configuration file!`
I've set up ci for the documentation, so please @ me if you have questions.

**Comment by lzw-723** [comment]
plz write your documents in https://github.com/pur1fying/blue_archive_auto_script/tree/master/docs

Just edit it, Github Actions will automatically deploy.

**Comment by pur1fying** [comment]
@lzw-723 OK，thank you o(*￣▽￣*)ブ

**Comment by lzw-723** [comment]
I updated the docs, so change this repo's website url to https://pur1fying.github.io/blue_archive_auto_script/
Let more users know it.

: )
