### ISSUE TITLE
[Bug] 体力溢出时无法正确识别点击

### ISSUE THREAD

**Issue by SummonHIM** [pur1fying/blue_archive_auto_script#79]
体力溢出时无法识别并点击确定。
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/431eff65-b123-42fc-a195-df72aa9dea71)

有些关卡体力溢出也是打不了的，也是一样会卡住。

**Comment by pur1fying** [comment]
请发模拟器1280x720截图

**Comment by SummonHIM** [comment]
商店
![Screenshot_2024 03 17_12 04 36 100](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/16feeb70-ec4e-408f-a2cc-9512c37dc20d)
任务
![Screenshot_2024 03 17_12 05 47 850](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/b12696ef-e3b8-429f-992a-1b4880656606)
咖啡厅
![Screenshot_2024 03 17_13 11 00 237](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/fc74bcd3-0e49-4bbe-b74c-ebdafe787f9c)
竞技场。竞技场是满体力无论如何都领取不了时间报酬和Daily报酬。
![Screenshot_2024 03 17_14 44 42 113](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/aa06643a-0149-4d43-85b1-48a37ed810aa)

**Comment by SummonHIM** [comment]
还有一个无关标题的问题是
![Screenshot_2024 03 17_14 40 08 277](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/28ef676e-e76d-4710-8602-6bb35d9f10ca)
手动打了一次竞技场后在用脚本打。战斗待机提示也无法识别

**Comment by pur1fying** [comment]
看了一下日服图片资源。
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/be0a91f6-0bd4-457c-9946-b71b97bbccbe)

这一张弹窗是有录入并且应该会识别点击关闭的。 /src/images/JP/main_page/full-notice
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/de6deb82-1f15-4c92-bcce-3cb3b1aef6fe)
zhe'yi'zhang
这一张弹窗已经加入并更新资源。/src/images/JP/main_page/insufficient-inventory-space
如果更新后还有卡住可以发下日志(我目前借别人的日服账号号主比较勤快，一般体力不会满所以没法测试)。

竞技场人为打完一次在立即启动baas是会有这个问题，但是一般人不会这么做就没考虑（未来闲暇可能会修复

**Comment by SummonHIM** [comment]
请问下有更新吗，这边战术对抗商店还是会卡住

**Comment by pur1fying** [comment]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/51e193c6-dfbb-4c5c-9571-c8e27dc2a8c2)
刚刚测试了一下日服jjc商店出现999体力溢出是会关闭的，你还是会卡住？

**Comment by SummonHIM** [comment]
> ![image](https://private-user-images.githubusercontent.com/139786997/316311753-51e193c6-dfbb-4c5c-9571-c8e27dc2a8c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODcxMDEsIm5iZiI6MTcxMTI4NjgwMSwicGF0aCI6Ii8xMzk3ODY5OTcvMzE2MzExNzUzLTUxZTE5M2M2LWRmYmItNGM1Yy05NTcxLWM4ZTI3ZGMyYThjMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzI2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTgyYmVmMjIxZTJlZjUwYzZjYzg2YjFhNjhmNjVjMmI3ZWY2YjVhNGU2OTVlNDhhYmQwYjMxOGM4NDk4M2VlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qNdR2u25q-d4SPr271LyHYDBsMLJL5i_booR2gjrOvs) 刚刚测试了一下日服jjc商店出现999体力溢出是会关闭的，你还是会卡住？

是的 还是说需要720P？

**Comment by pur1fying** [comment]
@SummonHIM 看看日志

**Comment by SummonHIM** [comment]
> @SummonHIM 看看日志

刚清完 明天我给个

**Comment by SummonHIM** [comment]
```
    INFO | 2024-03-25 15:40:44.820258 | asset_required : 235 
    INFO | 2024-03-25 15:40:44.820772 | click (857 , 461) 
    INFO | 2024-03-25 15:40:45.032076 | click (1000 , 461) 
    INFO | 2024-03-25 15:40:45.244401 | click (1162 , 461) 
    INFO | 2024-03-25 15:40:45.454715 | SWIPE DOWNWARDS 
    INFO | 2024-03-25 15:40:45.454715 | swipe from ( 932 , 550 ) --> ( 932 , 0 ) 
    INFO | 2024-03-25 15:40:46.998847 | click (700 , 204) 
    INFO | 2024-03-25 15:40:47.210481 | click (857 , 204) 
    INFO | 2024-03-25 15:40:47.421318 | click (1000 , 204) 
    INFO | 2024-03-25 15:40:48.063396 | Purchase available 
    INFO | 2024-03-25 15:40:48.064422 | click (1160 , 662) 
    INFO | 2024-03-25 15:40:48.674966 | click (767 , 488) 
    INFO | 2024-03-25 15:40:50.787590 | click (640 , 80 ) 
    INFO | 2024-03-25 15:40:50.900196 | click (640 , 80 ) 
    INFO | 2024-03-25 15:40:51.069678 | left assets : 3788 
    INFO | 2024-03-25 15:40:51.512350 | end : tactical_challenge_shop 
    INFO | 2024-03-25 15:40:51.817570 | Refresh assets adequate 
```
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/b11a3d17-cffe-4781-a2e9-569948180c8d)

**Comment by pur1fying** [comment]
emm，我知道原因了，一言难尽，已修复，明天再试试吧

**Comment by SummonHIM** [comment]
> emm，我知道原因了，一言难尽，已修复，明天再试试吧

好的 多谢 我明天试试

**Comment by SummonHIM** [comment]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/33192611/7a99882f-659c-4452-bfbf-efcbf30e974a)
这玩意也没识别出来
但我点了就没了 720p估计得下次活动才能截了

**Comment by SummonHIM** [comment]
> emm，我知道原因了，一言难尽，已修复，明天再试试吧

体力溢出识别已正常 多谢大佬
