### ISSUE TITLE
启动后重复点击操作

### ISSUE THREAD

**Issue by Ayusummer** [pur1fying/blue_archive_auto_script#81]
如图所示, 点击启动后反复尝试点击右上角, 没有其他动作是为什么呢?是因为我功能还没开全的缘故么?

![image](https://github.com/pur1fying/blue_archive_auto_script/assets/59549826/6eeabfac-0015-4fed-a97f-5c8b416bc56d)

**Comment by pur1fying** [comment]
关闭后台保活，教学视频中有

**Comment by Dreamwxz** [comment]
使用爱露也会出现此bug
