### ISSUE TITLE
启动后一直进行该动作

### ISSUE THREAD

**Issue by TheZhiheng223** [pur1fying/blue_archive_auto_script#87]
![图片](https://github.com/pur1fying/blue_archive_auto_script/assets/46839651/bc93c80d-1530-406c-bd23-0178b36829e9)

**Comment by TheZhiheng223** [comment]
![图片](https://github.com/pur1fying/blue_archive_auto_script/assets/46839651/83f1170e-c160-49ed-b125-f96c12491b63)

**Comment by pur1fying** [comment]
对照教程做
