### ISSUE TITLE
功能请求 momo_talk

### ISSUE THREAD

**Issue by fuyqz** [pur1fying/blue_archive_auto_script#90]
求开放一键momo_talk功能

**Comment by pur1fying** [comment]
什么意思，有这个功能啊？

**Comment by fuyqz** [comment]
没看到啊，剧情里面只有主线小组和支线啊

**Comment by pur1fying** [comment]
在调度器里

**Comment by pur1fying** [comment]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/cb1515e8-a2ee-443c-a726-83a0ad24306a)

**Comment by fuyqz** [comment]
sorry，我的问题，这还能往下滑动的啊。
