### ISSUE TITLE
领17点登陆奖励逻辑修改为执行两次

### ISSUE THREAD

**Issue by heidon-sensei** [pur1fying/blue_archive_auto_script#91]
由于BA的机制，有时候脚本执行完领取奖励的任务后17点登陆弹窗才会出现（此时才可以领取奖励），所以，领取奖励可以改成执行两次，不用进行过多修改

**Comment by pur1fying** [comment]
新版调度器中把领取体力刷新时间改为17:01(国服18:01)，麻烦再看看有没有问题

**Comment by heidon-sensei** [comment]
> 新版调度器中把领取体力刷新时间改为17:01(国服18:01)，麻烦再看看有没有问题

感觉问题其实在于，后台挂机一段时间后，第一次领体力BA会反应不过来，要两次才行

**Comment by heidon-sensei** [comment]
然后这个问题又牵扯到BAAS于模拟器的通讯，不知道是BAAS这类py脚本的特性还是mumu模拟器的原因，经常会出现挂完一个晚上之后BA点不动（不只晚上，一旦长时间不操作就似乎会有这种问题，稳定复现），并且有时候附带BAAS与BA通讯出问题提示invailed virson（不知道写的对不对），不出现这个error的话就脚本卡在某个地方不动

**Comment by heidon-sensei** [comment]
> > 新版调度器中把领取体力刷新时间改为17:01(国服18:01)，麻烦再看看有没有问题
> 
> 感觉问题其实在于，后台挂机一段时间后，第一次领体力BA会反应不过来，要两次才行

只领一次还没试过，但领两次似乎没问题

**Comment by heidon-sensei** [comment]
> 然后这个问题又牵扯到BAAS于模拟器的通讯，不知道是BAAS这类py脚本的特性还是mumu模拟器的原因，经常会出现挂完一个晚上之后BA点不动（不只晚上，一旦长时间不操作就似乎会有这种问题，稳定复现），并且有时候附带BAAS与BA通讯出问题提示invailed virson（不知道写的对不对），不出现这个error的话就脚本卡在某个地方不动

以下为长期以来的多次测试记录（开了mumu的非主窗口降低帧率，笔记本关盖已设置为仅熄屏）

早期  jjc显示5天前（周一最后运行）
操作1：只保留模拟器和BAAS，模拟器声音关闭，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
操作2：只保留模拟器和BAAS，模拟器声音关闭，BAAS最小化到状态栏，电脑关盖运行
结果：模拟器和BAAS均崩溃

2024/3/24晚—29晚  jjc显示4天前（周二最后运行）
第一次保持模拟器和BAAS进程不掉线
操作：不定时开风扇吹风，只保留模拟器和BAAS，模拟器声音关闭，开启操作录制执行1d循环，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
结果：脚本最后在周一生效，卡在油管跳转失败界面，BAAS程序卡停

2024/3/30 21:50—22:50 1h
模拟器与BAAS均正常运行
操作：无风扇，只保留模拟器和BAAS，模拟器声音关闭，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
项目：领邮箱22：00  普通商店2：20  jjc22：35  收集奖励22：45
结果：正常

2024/3/31 1:10—11:10 10h
模拟器与BAAS均正常运行
操作：无风扇，只保留模拟器和BAAS，模拟器声音关闭，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
结果：正常

2024/3/31晚—4/3晚
模拟器与BAAS进程均未掉线，但BA未运行
操作：早晚开风扇，只保留模拟器和BAAS，模拟器声音关闭，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
结果：2024/4/1脚本最后一次生效，卡在桌面，BA未运行（经研究后发现是BA初始界面loading持续过长时间后卡退），BAAS卡停

2024/4/5晚12—6早12
模拟器与BAAS进程均未掉线，但点击失效
操作：无风扇，电脑正常使用，电脑不关盖运行，模拟器声音开启，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏
结果：2024/4/6 09:09运行咖啡厅模块时点击失效，脚本输出点击指令但模拟器未有点击操作，重新执行脚本后正常

2024/4/6晚—4/12早 jjc显示6天前（周六最后运行）
未知状况4/·10人为关闭
操作：早晚开风扇，只保留模拟器和BAAS，模拟器声音关闭，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
结果：2024/4/6脚本最后一次生效
2024/4/21晚—4/26早 jjc显示5天前（周日最后运行）
模拟器窗口存在，但BAAS显示设备掉线
操作：早晚开风扇，只保留模拟器和BAAS，模拟器声音关闭，开启操作录制执行1d循环，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏，电脑关盖运行
结果：2024/4/22脚本最后一次推进

2024/5/5晚—5/11晚
模拟器与BAAS进程均未掉线，但脚本停滞
操作：早晚开风扇，开机自启动软件全开，开启性能模式，电脑关盖运行，模拟器声音开启，开启操作录制执行1d循环，老板键隐藏模拟器窗口运行，BAAS最小化到状态栏
结果：2024/5/6 03:00进行重启程序时，卡在日期更变弹窗，脚本未响应，手动点击弹窗后正常
