### ISSUE TITLE
调度中“下次刷新时间”更新错误导致任务一直运行

### ISSUE THREAD

**Issue by ryujou** [pur1fying/blue_archive_auto_script#93]
### 配置详情如下
![屏幕截图 2024-05-22 075325](https://github.com/pur1fying/blue_archive_auto_script/assets/30500241/134a0b64-4ab1-4e82-81d1-3aa5759b9951)
### 手动设置刷新时间为2524-5-22 4:00
![屏幕截图 2024-05-22 081111](https://github.com/pur1fying/blue_archive_auto_script/assets/30500241/20693fe6-6900-42cf-a5dc-1abcc7288505)

### 自动运行完一轮任务之后又从头开始运行新一轮任务，刷新时间变为，导致任务一直运行

![屏幕截图 2024-05-22 081125](https://github.com/pur1fying/blue_archive_auto_script/assets/30500241/d77287b7-8cc3-46d2-b96c-98ac3727b51f)

**Comment by pur1fying** [comment]
麻烦再试一下，已做出一定修复

**Comment by ryujou** [comment]
可以了，感谢大佬的修复
