### ISSUE TITLE
一直卡在这个点击页面

### ISSUE THREAD

**Issue by Just-Miku094** [pur1fying/blue_archive_auto_script#95]
![捕获](https://github.com/pur1fying/blue_archive_auto_script/assets/127653375/efa28d53-45d8-47ed-ae05-36d190eefec9)
![MuMu12-20240528-225646](https://github.com/pur1fying/blue_archive_auto_script/assets/127653375/3bc5ce56-bf46-431e-a7f6-b8801e3853b0)

**Comment by pur1fying** [comment]
#81 看下是不是这个原因

**Comment by voidzero42** [comment]
https://blog.lzwi.fun/blue_archive_auto_script/faq.html
