### ISSUE TITLE
运行悬赏通缉时会闪退

### ISSUE THREAD

**Issue by yukiryo** [pur1fying/blue_archive_auto_script#96]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/58250223/53d59cf2-2cdd-4107-be36-eff48ce6aabd)
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/58250223/9e6645d3-cd3e-4628-9e9a-3a15934b0a21)

**Comment by pur1fying** [comment]
已经修复, 错误来自这个commit
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/139786997/f38ecacc-b840-46d4-aa0e-da5c7724cf12)
