### ISSUE TITLE
国服重建对策委员会活动问题

### ISSUE THREAD

**Issue by Yinr** [pur1fying/blue_archive_auto_script#98]
国服重建对策委员会活动遇到以下两个问题，在我这边稳定触发，但不确定是不是我这边个人的问题

1. 任务扫荡 08-12 关时不会将列表滑到最后，导致点击对应关卡时可能无法点上或者点到其他关卡
2. 兑换奖励全部抽完后不会自动返回，一直停留在抽奖界面，手动返回后才继续去打气垫船

暂时没有太多时间去拜读源码，所以不好瞎改，就来提 issue 看看是不是我个人的问题 😂

**Comment by pur1fying** [comment]
1.在我这里可以滑到最底，如果有视频可以看看具体是怎么没滑到最后
2.已修复

**Comment by Yinr** [comment]
可能我电脑太老了配置低模拟器反应慢的原因，视频如下，就是一次上滑没有滑到底导致的错位。

我设置的是 `9,10,11,12` 各 `1/4` 体力

https://github.com/pur1fying/blue_archive_auto_script/assets/9482504/3b7ff712-7c36-4fa5-8b41-d296412ab9af

**Comment by pur1fying** [comment]
好的，后续会考虑低配电脑滑动包括点击不到位的问题

**Comment by pur1fying** [comment]
已添加

**Comment by Yinr** [comment]
感谢~不过没来得及赶上测试 😂
