### ISSUE TITLE
应用总是在拖动自动制造中优先级的过程中闪退

### ISSUE THREAD

**Issue by Taka499** [pur1fying/blue_archive_auto_script#99]
![image](https://github.com/pur1fying/blue_archive_auto_script/assets/14145862/f342d1e3-2d13-4bc5-a82e-e0db177ba9e4)
请问这个优先级编排功能可以优化一下吗？现在非常难用，需要一个一个缓慢的拖动到最前方。

**Comment by Kiramei** [comment]
这个问题一般是环境中存在两个相同的库，其动态链接重复错误而导致的，我建议可以尝试在你`window.py`文件的库文件引入之后加上：
```python

os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

```

**Comment by Kiramei** [comment]
@Taka499 请问问题解决了吗？
